In [ ]:
import numpy as np

# range() 범위 지정
# reshape(x,y) x 행 y 열 로 만듬
a = np.arange(15).reshape(3, 5)
# print(a)

# print(a.shape) # x 행 y 열 알려줌
# print(a.dtype.name) # 자료형 확인
# print(a.itemsize) # 크기
# print(a.size) # 크기

# np.array() 로 선언도 가능함
b = np.array([6, 7, 8])
# print(b)

# 여러가지 형을 넣을수있지만 문자가 들어가면 정수도 다 문자로 바뀜
c = np.array([1, "two", 3, 4])
# print(c) # ['1' 'two' '3' '4']

# float 형태로도 선언이 가능
a = np.array([1.2, 3.5, 5.1, 3])
# print(a)

# list 와 np.array 는 다르지만 사용하는 방법은 크게 다르지않음
a = [2, 4, 5]
aa = np.array(a)
a  # [2, 4, 5]
aa  # array([2, 4, 5])
aa[1]  # 4
a[1]  # 4

# 배열의 복사
arr = np.arange(10)
arr  # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[5]  # 5
arr[5:8] = 12  # 배열의 5~7번지 까지 12로 변경
arr  # array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

arr_slice = arr[5:8]
arr_slice  # array([12, 12, 12])

arr_slice[:] = 65  # 전체를 65로 만들기
arr_slice  # [65, 65, 65]

arr_slice_copy = (
    arr_slice.copy()
)  # copy() 함수를 사용하여 복사 대상 배열의 값이 변경되면 같이 변경됨
arr_slice_copy  # [65, 65, 65]

# array 를 만드는 함수들
a2 = np.zeros(3)  # 1 차원 배열을 변수만큼의 0으로 생성
a2  # array([0., 0., 0.])

a3 = np.ones(3)  # 1 차원 배열을 변수만큼의 1로 생성
a3  # array([1., 1., 1.])

k1 = np.eye(3)  # x 행 x 열 단위행렬 생성
k1  # array([[1., 0., 0.],
#       [0., 1., 0.],
#       [0., 0., 1.]])

# 배열의 차원 형태 변경
c = np.arange(1, 5)
c  # array([1, 2, 3, 4]) / 1차원 배열임
c.shape = (2, 2)  # c 배열의 형태를 2행 2열로 바꿈
c  # array([[1, 2],
#        [3, 4]])
c.shape = (4,)  # 형태를 1행으로 바꿈
c  # array([1, 2, 3, 4])

c = np.full((2, 2), 3)  # 형태를 2행 2열로 바꾸며 값은 3으로 바꿈
c  # array([[3, 3],
#        [3, 3]])

k = np.random.random((2, 2))  # 0~1 사이 랜덤값을 2행 2열로 채움

na = np.arange(1, 9)
na.reshape(2, 4)  # na.shape = (2,4) 와 같음

# 배열의 번지수 출력하기
a = na.reshape(2, 4)
a[1, 1]  # 6
a[1][1]  # 6

# 3차원 배열
array = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
        [[0, 1, 2, 3], [4, 5, 100, 7], [8, 9, 10, 11]],
    ]
)

array.shape  # (2,3,4) 3 x 4 배열이 2개있다는 의미
array[1, 1, 2]  # 100

100

In [ ]:
# 배열의 사칙연산
# 배열의 사칙연산은 shape 가 동일해야함 (행과 열이 동일해야함)
x = np.array([[1, 2], [3, 4]], dtype=np.float64)  # 2행 2열의 실수형 배열 선언
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

x + y  # 각 행 열에 대응되는 값끼리 더함
np.add(x, y)  # x + y 를 add 함수를 사용함

x - y  # 각 행 열에 대응되는 값끼리 뺄셈
np.subtract(x, y)  # x - y 를 subtract 함수를 사용함

x * y  # 각 행 열에 대응되는 값끼리 곱셈
np.multiply(x, y)  # x * y 를 multiply 함수를 사용

x / y  # 각 행 열에 대응되는 값끼리 나눗셈
np.divide(x, y)  # x / y 를 divide 함수를 사용

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
# 사칙연산 실사용 예제

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 백터의 내적 구하기 dot() 함수
v.dot(w)  # 219
np.dot(v, w)  # 219

x.dot(v)  # array([29, 67])
np.dot(x, v)  # array([29, 67])

# 1
a = np.array([1, 2, 3])
b = np.arange(3, 6)

type(a)  # numpy.ndarray
2 * a  # array([2, 4, 6]) / 리스트는 * 할때 요소 갯수가 곱해지지만 배열은 각 요소 값이 곱해짐
a + b  # array([4, 6, 8])

# 2
c = np.array([[1, 2, 3], [4, 5, 6]])
c.size  # 6 (원소의 갯수)
c.shape  # (2,3) 2행 3열짜리 배열

d = np.arange(10).reshape(2, 5)  # 0~9 까지 2행 5열 형태로

e = np.arange(2, 3, 0.1)  # 2~3 까지 스탭은 0.1 로 만들기
e  # array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

# 2 배열 생성하면서 초기화 하기
a = np.zeros((2, 2), int)  # 2행 2열 배열을 0으로 채우기
a  # array([[0, 0],
#        [0, 0]])

b = np.zeros((2, 2), float)  # 이번엔 실수로 채우기

c = np.ones((2, 2), int)  # 1로 채우기
d = np.ones((2, 2), float)

d = np.full((2, 2), 7)  # 7로 채우기
e = np.eye(2)  # 대각선 방향으로 1로 채움! 변수만큼 행 열 이 생성됨

f = np.random.random((2, 2))  # 0~1 난수로 채우기

array([[0.45051191, 0.81817326],
       [0.05866334, 0.36990258]])

In [195]:
# 배열의 인덱싱

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [3, 10, 11, 12]])
a[0, 0]  # 1
a[(0, 0)]  # 1
a[0][0]  # 1

a[1, 2]  # 7
a[-1, -1]  # 12
a[-1, -1] += 10  # 마지막 원소에 + 10 해버리기

# 배열의 슬라이싱
a[1, :]  # 1행의 모든열
a[:2, :]  # 2행 까지의 모든열

a[:2, 1:3]  # 2행 까지의 1~2열 만

a[:, 0:3:2]  # 모든행 0~2 열까지 스탭은 2

a[:, -1:-4:-2]  # 모든행 뒤에서 부터 앞까지 스탭은 2
a[:, [3, 0, 2, 1]]  # 모든행을 지정한 순서대로
a[[0, 1, 2], [0, 1, 2]]  # 0,1,2 번행의 0,1,2 번지

array([ 1,  6, 11])

In [231]:
import numpy as np

a > 5  # 원소중에 5보다 큰것인지 bool 형으로 나타남
b = a[a > 5]  # 원소중에 5보다 큰것만 뽑아서 1차원 배열로 나옴
b  # array([ 6,  7,  8, 10, 11, 22])

b = a[:]
b[b % 2 == 0]  # b의 원소중에 짝수만 가져옴

c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.arange(11, 17).reshape(2, 3)

c + d
c - d
c * d
c / d

c**2  # c 배열의 원소를 각각제곱
np.sqrt(c)  # c 배열의 원소를 각각 루트연산.
np.dot(c, d.transpose())
np.dot(c.T, d)

array([[ 67,  72,  77],
       [ 92,  99, 106],
       [117, 126, 135]])

In [ ]:
# numpy 의 내부 수학/통계 함수
list1 = [3, 5.6, 5.8, 9.5]

array = np.array(list1)
array.mean()  # 평균
array.sum()  # 각 요소 덧셈
array.max()  # 최댓값
array.min()  # 최솟값
array.var()  # 분산
array.std()  # 표준편차

2.3155722834755124

In [ ]:
# 자료형
ar = np.array([1, 2, 3])
ar.dtype  # int32

ar = np.array(["12", "2", "3"])
ar.dtype  # <U2

ar2 = np.array([1.5, 2.0, 3.5])
ar2.dtype  # float64

ar3 = np.array([1, 2, 3, "4"])
ar3.dtype  # <U11

# 자료형의 형변환
ar = np.array(
    [False, True, False, True], dtype=np.int32
)  # bool 자료형을 int 로 바꾸므로 False = 0 True = 1
ar  # array([0, 1, 0, 1])

1

In [324]:
# 1 숫자 15에서 23까지 배열을 만들고 이를 3 * 3 행렬로 변환하여 출력하라
array = np.arange(15, 24).reshape(3, 3)
print(f"1 : {array}")

# 2 다음의 2 array를 만들고 위의 두 array를 이용해서 아래와 같은 값이 나오게
# 목표 : [False, False, False, False]
arr1 = np.arange(1, 5)
arr2 = np.arange(5, 9)
list1 = [x == y for x, y in zip(arr1, arr2)]
print(f"2 : {list1}")
# 3 각 중간 기말 과제점수의 가중치의 합을 구하고 거기에 기타점수 5점을 더함
# 중간고사 평균과 표준편차를 구하고 철수의 최종점수도 구해요
사람 = np.array(["철수", "영희", "민재"])
중간고사 = np.array([15, 100, 45])
기말고사 = np.array([78, 25, 90])
과제 = np.array([81, 45, 99])
가중치 = np.array([0.4, 0.4, 0.2])
print(f"3 : 중간고사 평균 : {중간고사.mean():.1f} 표준편차 : {중간고사.std():.1f}")


최종점수 = (중간고사 * 가중치[0]) + (기말고사 * 가중치[1]) + (과제 * 가중치[2]) + 5
for name, score in zip(사람, 최종점수):
    print(f"{name}의 최종 점수 {score:.1f}")

1 : [[15 16 17]
 [18 19 20]
 [21 22 23]]
2 : [False, False, False, False]
3 : 중간고사 평균 : 53.3 표준편차 : 35.2
철수의 최종 점수 58.4
영희의 최종 점수 64.0
민재의 최종 점수 78.8


In [ ]:
# 연습문제2
# 1 1차원 배열 생성 및 연산
# 숫자 10부터 30까지의 배열을 생서하고, 배열 내 모든값에 2를 곱한 결과를 출력하세요
array = np.arange(10, 31) * 2
print("1.\n", array)

# 2 다차원 배열 생성 및 변환
# 1) 숫자 0부터 15까지 포함하는 1차원 배열을 생성하세요
# 2) 이를 4 x 4 행렬로 반환하세요
array = np.arange(16).reshape(4, 4)
print("2.\n", array)

# 3 특정 조건에 맞는 값 필터링
# 1부터 20까지의 배열에서 짝무나 추출하여 새 배열을 생성하세요
array = np.arange(1, 21)
array = array[array % 2 == 0]
print("3.\n", array)

# 4 배열 연산 및 집계 함수 활용
# 1) 임의의 3*3 배열을 생성하세요
# 2) 각 행의 합계와 평균을 구하고 출력하세요
arr1 = np.random.randint(1, 10, (3, 3))

# axis = 1 행 axis = 0 열
print("4-1. 배열\n", arr1)
print("4-2. 합계\n", arr1.sum(axis=1))
print("4-3. 평균\n", arr1.mean(axis=1))

# 5 행렬 곱센 및 정구화
# 1) 3*3 단위 행렬을 생성하세요
# 2) 다른 3*3 행렬을 만들어 행렬의 곱을 구하세요
arr1 = np.eye(3)  # 단위행렬 생성
arr2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
result = np.dot(arr1, arr2)
print("5.\n", result)

1.
 [20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]
2.
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
3.
 [ 2  4  6  8 10 12 14 16 18 20]
4-1. 배열
 [[1 3 4]
 [2 3 2]
 [8 5 9]]
4-2. 합계
 [11 11 15]
4-3. 평균
 [2.66666667 2.33333333 7.33333333]
5.
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
